### ISSUE TITLE
GitHub Actions and Appveyor give 404's on installer run

### ISSUE THREAD

**Issue by D3PSI** [D3PSI/pbrrenderer#2]

**Comment by Pluscrafter** [comment]
adding 
`sudo apt update`
before installing the packages should fix the problem.
Source: [https://askubuntu.com/questions/1159096/ubunutu-18-04-updates-404-error](url)

**Comment by D3PSI** [comment]
Closed via #[70c4de](https://github.com/D3PSI/pbrrenderer/commit/70c4decb833aec2301e91b34e8efb584cc5b9e29)
